# 优先级4
top:
  gabin:
    # idea中，file encoding需要配置一下配置文件的编码，避免乱码
    name: '林嘉斌'
    mail: 405424652@qq.com
    securityKey: ${random.uuid}
server:
  # 如果是微服务架构，是不关心端口号的，随机取个端口号也是可以的
  port: ${random.int(8080,10000)}