server:
  # 如果是微服务架构，是不关心端口号的，随机取个端口号也是可以的
  port: 8083
spring:
  datasource:
    probation:
      username: root
      password:
      url: jdbc:mysql://localhost:3306/hr_probation?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    questionnaire:
      username: root
      password:
      url: jdbc:mysql://localhost:3306/hr_questionnaire?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver